# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_ou <- function(t_max, x_t0, dt, theta, omega, mu) {
    .Call(`_sdelib_r_ou`, t_max, x_t0, dt, theta, omega, mu)
}

