// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// r_ou
arma::dvec r_ou(const double& t_max, const double& x_t0, const double& dt, const double& theta, const double& omega, const double& mu);
RcppExport SEXP _sdelib_r_ou(SEXP t_maxSEXP, SEXP x_t0SEXP, SEXP dtSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< const double& >::type x_t0(x_t0SEXP);
    Rcpp::traits::input_parameter< const double& >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< const double& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const double& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(r_ou(t_max, x_t0, dt, theta, omega, mu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sdelib_r_ou", (DL_FUNC) &_sdelib_r_ou, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_sdelib(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
